# https://travis-ci.com/ContinuumIO/ciocheck

language: python
sudo: false

env:
  global:
    # Used by qthelpers to close widgets after a defined time
    - TEST_CI="True"
    # Environment variables used by astropy helpers
    - CONDA_CHANNELS="conda-forge continuumcrew"
    - CONDA_DEPENDENCIES="autopep8>=1.2 coverage>=4.2 flake8>=3.0 isort>=4.2 pydocstyle>=1.1 pylint>=1.6 pytest>=3.0 pytest-cov>=2.4 pytest-json>=0.4 pytest-xdist>=1.15 six>=1.10 yapf>=0.12"
    - PIP_DEPENDENCIES="coveralls"

matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5

install:
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - python setup.py develop

script:
  - ciocheck ciocheck

after_success:
  - coveralls
