package:
  name: ciocheck
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  git_tag: {{ environ.get('GIT_DESCRIBE_TAG') }}

build:
  noarch_python: True
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - coverage
    - flake8
    - isort
    - pydocstyle
    - pytest
    - pytest-cov
    - pytest-xdist
    - yapf

about:
  home: https://github.com/ContinuumIO/ciocheck
  summary: "Continuum check/test suite helper"
  dev_url: https://github.com/ContinuumIO/ciocheck
