package:
  name: ciocheck
  version: '0.2'

build:
  noarch_python: True
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - coverage
    - flake8
    - isort
    - pydocstyle
    - pylint
    - pytest
    - pytest-cov
    - pytest-json
    - pytest-xdist
    - yapf

about:
  home: https://github.com/ContinuumIO/ciocheck
  summary: "Continuum check/test suite helper"
  license: MIT
  dev_url: https://github.com/ContinuumIO/ciocheck
